name: Test self-hosted

on: [push]
jobs:
  test:
    runs-on: self-hosted
    env:
      SECRET_DEV: ${{ secrets.DEV_TOKEN }}
    steps:
      - name: Comparar DEV_TOKEN con LOCAL_DEV_TOKEN
        run: |
          echo "Comparando el secret de GitHub con la variable local."
          if (($env:SECRET_DEV -eq $env:LOCAL_DEV_TOKEN)){
            echo "Los token coinciden."
          } else {
            echo "Error: Los token no coinciden."
            exit 1
           }
            


          
