name: Validar Token Local

on: [push]

jobs:
  validar-tokens:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Comparar DEV_TOKEN y LOCAL_DEV_TOKEN
        shell: powershell
        run: |
          Write-Host "Comprobando el secret de GitHub con la variable local."
          if ($env:TOKEN -eq $env:LOCAL_DEV_TOKEN) {
            Write-Host "CI: Los token coinciden."
          } else {
            Write-Host "CI: Los token no coinciden"
            exit 1
          }
        env:
          TOKEN: ${{ secrets.DEV_TOKEN }}